# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNX0dhSP9A0W8Iw87mTm4uqe3OLCgYPo
"""

import numpy as np


class Perceptron(object):
  '''Basic perceptron classifier'''
  '''
  ---------Parameters--------
  eta: float - learning rate 0<eta<1
  iter_number: int - iteration over dataset
  random_state: int - RNG seed
  ---------Attributes--------
  w_: ld-array - weights after fitting
  errs_ : list - number of misclassifications for each epoch
  '''

